changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
